// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_derivedTypes_ProducerConsumer_components_interfaces_CPullConsumer_PubData_BODY

/************************************************************
 CPullConsumer_PubData class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/CPullConsumer_PubData.h"

// Derived includes directives
#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/PullConsumer_PubData.h"

namespace ProducerConsumer {
namespace derivedTypes {
namespace ProducerConsumer {
namespace components {
namespace interfaces {

// static attributes (if any)

}// of namespace interfaces
} // of namespace components
} // of namespace ProducerConsumer
} // of namespace derivedTypes
} // of namespace ProducerConsumer

/************************************************************
 End of CPullConsumer_PubData class body
 ************************************************************/
