// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_CPUSH_PUBDATA_H
#define PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_CPUSH_PUBDATA_H

/************************************************************
 CPush_PubData class header
 ************************************************************/

#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Pkg_interfaces.h"

namespace ProducerConsumer {
namespace derivedTypes {
namespace ProducerConsumer {
namespace components {
namespace interfaces {

/************************************************************/
/**
 * 
 */
class CPush_PubData {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaces
} // of namespace components
} // of namespace ProducerConsumer
} // of namespace derivedTypes
} // of namespace ProducerConsumer

/************************************************************
 End of CPush_PubData class header
 ************************************************************/

#endif
