// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_PULLCONSUMER_PUBDATA_H
#define PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_PULLCONSUMER_PUBDATA_H

/************************************************************
 PullConsumer_PubData class header
 ************************************************************/

#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Pkg_interfaces.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {
struct PubData;
}
}
}

namespace ProducerConsumer {
namespace derivedTypes {
namespace ProducerConsumer {
namespace components {
namespace interfaces {

/************************************************************/
/**
 * 
 */
class PullConsumer_PubData {
public:

	/**
	 * 
	 * @return ret 
	 */
	virtual ::ProducerConsumer::components::interfaces::PubData pull() = 0;

	/**
	 * 
	 * @return ret 
	 */
	virtual ::PrimitiveTypes::Boolean hasData() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaces
} // of namespace components
} // of namespace ProducerConsumer
} // of namespace derivedTypes
} // of namespace ProducerConsumer

/************************************************************
 End of PullConsumer_PubData class header
 ************************************************************/

#endif
