// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_PUSH_PUBDATA_H
#define PRODUCERCONSUMER_DERIVEDTYPES_PRODUCERCONSUMER_COMPONENTS_INTERFACES_PUSH_PUBDATA_H

/************************************************************
 Push_PubData class header
 ************************************************************/

#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Pkg_interfaces.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {
struct PubData;
}
}
}

namespace ProducerConsumer {
namespace derivedTypes {
namespace ProducerConsumer {
namespace components {
namespace interfaces {

/************************************************************/
/**
 * 
 */
class Push_PubData {
public:

	/**
	 * 
	 * @param data 
	 */
	virtual void push(
			::ProducerConsumer::components::interfaces::PubData /*in*/data) = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaces
} // of namespace components
} // of namespace ProducerConsumer
} // of namespace derivedTypes
} // of namespace ProducerConsumer

/************************************************************
 End of Push_PubData class header
 ************************************************************/

#endif
