// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_COMPONENTS_SERVER_CSERVER_IMPL_H
#define CLIENTSERVERZMQ_COMPONENTS_SERVER_CSERVER_IMPL_H

/************************************************************
 CServer_impl class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/components/Server/Pkg_Server.h>

#include <ClientServerZMQ/components/Interfaces/ICompute.h>

/* Owner package header include                             */
#include <corba/Pkg_corba.h>

namespace components {
namespace Server {

/************************************************************/
/**
 * 
 */

class CServer_impl: public ::ClientServerZMQ::components::Interfaces::ICompute {

public:

	/**
	 * 
	 */
	::ClientServerZMQ::components::Interfaces::ICompute p;

	/**
	 * 
	 * @param a @param b @param res 
	 */
	::corba::Long mult(::corba::Long /*in*/a, ::corba::Long /*in*/b);

	/**
	 * 
	 * @param a @param b @param res 
	 */
	::corba::Long add(::corba::Long /*in*/a, ::corba::Long /*in*/b);

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace Server
} // of namespace components

/************************************************************
 End of CServer_impl class header
 ************************************************************/

#endif
