// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_DataExchange_PubData_PullC_BODY

/************************************************************
 PullC class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/DataExchange_PubData/PullC.h"

// Derived includes directives

namespace ProducerConsumer {
namespace DataExchange_PubData {

// static attributes (if any)

}// of namespace DataExchange_PubData
} // of namespace ProducerConsumer

/************************************************************
 End of PullC class body
 ************************************************************/
