// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Class4_BODY

/************************************************************
 Class4 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Class4.h"

// Derived includes directives
#include "CppCodegenTest/Class3.h"

namespace CppCodegenTest {

// static attributes (if any)
/**
 * 
 */
char* Class4::charStringStaticInit = "Hello World";
/**
 * 
 */
const char* Class4::charStringStaticConstInit = "Hello World";

} // of namespace CppCodegenTest

/************************************************************
 End of Class4 class body
 ************************************************************/
