// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CPPCODEGENTEST_TESTSTL_H
#define CPPCODEGENTEST_TESTSTL_H

/************************************************************
 TestSTL class header
 ************************************************************/

#include "CppCodegenTest/Pkg_CppCodegenTest.h"

#include "string"

namespace CppCodegenTest {

/************************************************************/
/**
 * 
 */
class TestSTL {
public:
	/**
	 * 
	 */
	std::string str;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace CppCodegenTest

/************************************************************
 End of TestSTL class header
 ************************************************************/

#endif
