// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_TestSTL_BODY

/************************************************************
 TestSTL class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/TestSTL.h"

// Derived includes directives

namespace CppCodegenTest {

// static attributes (if any)

}// of namespace CppCodegenTest

/************************************************************
 End of TestSTL class body
 ************************************************************/
