// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_DATAEXCHANGE_PUBDATA_DERIVEDTYPES_FIFO_DATAEXCHANGE_PULLCONSUMER_T_H
#define PRODUCERCONSUMER_DATAEXCHANGE_PUBDATA_DERIVEDTYPES_FIFO_DATAEXCHANGE_PULLCONSUMER_T_H

/************************************************************
 PullConsumer_T class header
 ************************************************************/

#include "ProducerConsumer/DataExchange_PubData/derivedTypes/fifo/DataExchange/Pkg_DataExchange.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {
struct PubData;
}
}
}

namespace ProducerConsumer {
namespace DataExchange_PubData {
namespace derivedTypes {
namespace fifo {
namespace DataExchange {

/************************************************************/
/**
 * 
 */
class PullConsumer_T {
public:

	/**
	 * 
	 * @return ret 
	 */
	virtual ::ProducerConsumer::components::interfaces::PubData pull() = 0;

	/**
	 * 
	 * @return ret 
	 */
	virtual ::PrimitiveTypes::Boolean hasData() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace DataExchange
} // of namespace fifo
} // of namespace derivedTypes
} // of namespace DataExchange_PubData
} // of namespace ProducerConsumer

/************************************************************
 End of PullConsumer_T class header
 ************************************************************/

#endif
