// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_DATAEXCHANGE_PUBDATA_DERIVEDTYPES_FIFO_DATAEXCHANGE_PUSH_T_H
#define PRODUCERCONSUMER_DATAEXCHANGE_PUBDATA_DERIVEDTYPES_FIFO_DATAEXCHANGE_PUSH_T_H

/************************************************************
 Push_T class header
 ************************************************************/

#include "ProducerConsumer/DataExchange_PubData/derivedTypes/fifo/DataExchange/Pkg_DataExchange.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {
struct PubData;
}
}
}

namespace ProducerConsumer {
namespace DataExchange_PubData {
namespace derivedTypes {
namespace fifo {
namespace DataExchange {

/************************************************************/
/**
 * 
 */
class Push_T {
public:

	/**
	 * 
	 * @param data 
	 */
	virtual void push(
			::ProducerConsumer::components::interfaces::PubData /*in*/data) = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace DataExchange
} // of namespace fifo
} // of namespace derivedTypes
} // of namespace DataExchange_PubData
} // of namespace ProducerConsumer

/************************************************************
 End of Push_T class header
 ************************************************************/

#endif
