// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ClientServerZMQ_deployment_ConfigTraceMono_BODY

/************************************************************
 ConfigTraceMono class body
 ************************************************************/

// include associated header file
#include <ClientServerZMQ/deployment/ConfigTraceMono.h>

// Derived includes directives

namespace deployment {

// static attributes (if any)

}// of namespace deployment

/************************************************************
 End of ConfigTraceMono class body
 ************************************************************/