// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_DEPLOYMENT_CONFIGTRACEMONO_H
#define CLIENTSERVERZMQ_DEPLOYMENT_CONFIGTRACEMONO_H

/************************************************************
 ConfigTraceMono class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/deployment/Pkg_deployment.h>

namespace deployment {

/************************************************************/
/**
 * 
 */

class ConfigTraceMono {

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace deployment

/************************************************************
 End of ConfigTraceMono class header
 ************************************************************/

#endif
