// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_StdPorts_Cstart_BODY

/************************************************************
 Cstart class body
 ************************************************************/

// include associated header file
#include "componentlib/StdPorts/Cstart.h"

// Derived includes directives

namespace componentlib {
namespace StdPorts {

// static attributes (if any)

}// of namespace StdPorts
} // of namespace componentlib

/************************************************************
 End of Cstart class body
 ************************************************************/
