// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_COMPONENTS_CLIENT_CCLIENT_IMPL_H
#define CLIENTSERVERZMQ_COMPONENTS_CLIENT_CCLIENT_IMPL_H

/************************************************************
 CClient_impl class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/components/Client/Pkg_Client.h>

#include <ClientServerZMQ/components/Interfaces/ICompute.h>

#include <sysinterfaces/IStart.h>

#include <core/StdPorts/Cstart.h>

namespace components {
namespace Client {

/************************************************************/
/**
 * 
 */

class CClient_impl: public ::sysinterfaces::IStart,
		public ::core::StdPorts::Cstart {

public:

	/**
	 * 
	 */
	::ClientServerZMQ::components::Interfaces::ICompute q;

	/**
	 * 
	 * 
	 */
	void run();

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace Client
} // of namespace components

/************************************************************
 End of CClient_impl class header
 ************************************************************/

#endif
