// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_PortKinds_PushConsumer_BODY

/************************************************************
 PushConsumer class body
 ************************************************************/

// include associated header file
#include "componentlib/PortKinds/PushConsumer.h"

// Derived includes directives

namespace componentlib {
namespace PortKinds {

// static attributes (if any)

}// of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PushConsumer class body
 ************************************************************/
