// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_PORTKINDS_PUSHCONSUMER_H
#define COMPONENTLIB_PORTKINDS_PUSHCONSUMER_H

/************************************************************
 PushConsumer class header
 ************************************************************/

#include "componentlib/PortKinds/Pkg_PortKinds.h"

namespace componentlib {
namespace PortKinds {

/************************************************************/
/**
 * 
 */
class PushConsumer {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PushConsumer class header
 ************************************************************/

#endif
