// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_PortKinds_interfaceBased_ProvideInterface_BODY

/************************************************************
 ProvideInterface class body
 ************************************************************/

// include associated header file
#include "componentlib/PortKinds/interfaceBased/ProvideInterface.h"

// Derived includes directives
#include "componentlib/PortKinds/interfaceBased/I.h"

namespace componentlib {
namespace PortKinds {
namespace interfaceBased {

// static attributes (if any)

}// of namespace interfaceBased
} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of ProvideInterface class body
 ************************************************************/
