// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_PORTKINDS_INTERFACEBASED_PROVIDEINTERFACE_H
#define COMPONENTLIB_PORTKINDS_INTERFACEBASED_PROVIDEINTERFACE_H

/************************************************************
 ProvideInterface class header
 ************************************************************/

#include "componentlib/PortKinds/interfaceBased/Pkg_interfaceBased.h"

#include "componentlib/PortKinds/interfaceBased/I.h"

namespace componentlib {
namespace PortKinds {
namespace interfaceBased {

/************************************************************/
/**
 * 
 */
class ProvideInterface: public I {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaceBased
} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of ProvideInterface class header
 ************************************************************/

#endif
