// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_PortKinds_interfaceBased_UseInterface_BODY

/************************************************************
 UseInterface class body
 ************************************************************/

// include associated header file
#include "componentlib/PortKinds/interfaceBased/UseInterface.h"

// Derived includes directives

namespace componentlib {
namespace PortKinds {
namespace interfaceBased {

// static attributes (if any)

}// of namespace interfaceBased
} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of UseInterface class body
 ************************************************************/
