// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_PORTKINDS_INTERFACEBASED_USEINTERFACE_H
#define COMPONENTLIB_PORTKINDS_INTERFACEBASED_USEINTERFACE_H

/************************************************************
 UseInterface class header
 ************************************************************/

#include "componentlib/PortKinds/interfaceBased/Pkg_interfaceBased.h"

namespace componentlib {
namespace PortKinds {
namespace interfaceBased {

/************************************************************/
/**
 * 
 */
class UseInterface {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaceBased
} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of UseInterface class header
 ************************************************************/

#endif
