// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_DataExchange_PubData_FIFO_FIFO_impl_BODY

/************************************************************
 FIFO_impl class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/DataExchange_PubData/FIFO/FIFO_impl.h"

// Derived includes directives
#include "ProducerConsumer/DataExchange_PubData/derivedTypes/fifo/DataExchange/PullConsumer_T.h"
#include "ProducerConsumer/DataExchange_PubData/derivedTypes/fifo/DataExchange/Push_T.h"
#include "ProducerConsumer/components/interfaces/PubData.h"
#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/PullConsumer_PubData.h"
#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Push_PubData.h"
#include "sysinterfaces/ILifeCycle.h"

// Include from Include declaration (body)
#include <iostream>
using namespace std;
// End of Include declaration (body)

namespace ProducerConsumer {
namespace DataExchange_PubData {
namespace FIFO {

// static attributes (if any)

/**
 * 
 * @return ret 
 */
::ProducerConsumer::components::interfaces::PubData FIFO_impl::pull() {
	if (m_filled > 0) {
		int current_pos = m_pull_pos;

		m_pull_pos++;
		m_filled--;
		if (m_pull_pos == m_size) {
			m_pull_pos = 0;
		}
		return m_fifo[current_pos];
	}
}

/**
 * 
 * @param data 
 */
void FIFO_impl::push(
		::ProducerConsumer::components::interfaces::PubData /*in*/data) {
	// copy passed parameters ...
	if (m_filled < m_size) {
		m_fifo[m_push_pos] = data;
		m_push_pos++;
		m_filled++;
		if (m_push_pos == m_size) {
			m_push_pos = 0;
		}
	}
}

/**
 * 
 * @return ret 
 */
::PrimitiveTypes::Boolean FIFO_impl::hasData() {
	return (m_filled > 0);
}

/**
 * 
 */
void FIFO_impl::activate() {
	if (m_size == 0) {
		cerr << "Warning: size of FIFO is not properly configured (size = 0)"
				<< endl;
	}
	m_fifo = new ProducerConsumer::components::interfaces::PubData[m_size];
}

/**
 * 
 */
void FIFO_impl::deactivate() {
}

/**
 * 
 */
void FIFO_impl::configuration_complete() {
}

/**
 * 
 * @return ret 
 */
::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData* FIFO_impl::get_pushP() {
	return this;
}

/**
 * 
 * @return ret 
 */
::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::PullConsumer_PubData* FIFO_impl::get_pullC() {
	return this;
}

/**
 * 
 * @return ret 
 */
::sysinterfaces::ILifeCycle* FIFO_impl::get_lc() {
	return this;
}

} // of namespace FIFO
} // of namespace DataExchange_PubData
} // of namespace ProducerConsumer

/************************************************************
 End of FIFO_impl class body
 ************************************************************/
