// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_DERIVEDTYPES_SYSINTERFACES_USE_IRUNNABLE_H
#define COMPONENTLIB_DERIVEDTYPES_SYSINTERFACES_USE_IRUNNABLE_H

/************************************************************
 Use_IRunnable class header
 ************************************************************/

#include "componentlib/derivedTypes/sysinterfaces/Pkg_sysinterfaces.h"

namespace componentlib {
namespace derivedTypes {
namespace sysinterfaces {

/************************************************************/
/**
 * 
 */
class Use_IRunnable {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace sysinterfaces
} // of namespace derivedTypes
} // of namespace componentlib

/************************************************************
 End of Use_IRunnable class header
 ************************************************************/

#endif
