// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_derivedTypes_sysinterfaces_Use_IRunnable_BODY

/************************************************************
 Use_IRunnable class body
 ************************************************************/

// include associated header file
#include "componentlib/derivedTypes/sysinterfaces/Use_IRunnable.h"

// Derived includes directives
#include "sysinterfaces/IRunnable.h"

namespace componentlib {
namespace derivedTypes {
namespace sysinterfaces {

// static attributes (if any)

}// of namespace sysinterfaces
} // of namespace derivedTypes
} // of namespace componentlib

/************************************************************
 End of Use_IRunnable class body
 ************************************************************/
