// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_COMPONENTS_INTERFACES_PUBDATA_H
#define PRODUCERCONSUMER_COMPONENTS_INTERFACES_PUBDATA_H

/************************************************************
 PubData class header
 ************************************************************/

#include "ProducerConsumer/components/interfaces/Pkg_interfaces.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {

/************************************************************/
/**
 * 
 */
struct PubData {
	/**
	 * 
	 */
	long y;
	/**
	 * 
	 */
	long x;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace interfaces
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of PubData class header
 ************************************************************/

#endif
