// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_ContainerServices_LifeCycle_BODY

/************************************************************
 LifeCycle class body
 ************************************************************/

// include associated header file
#include "componentlib/ContainerServices/LifeCycle.h"

// Derived includes directives

namespace componentlib {
namespace ContainerServices {

// static attributes (if any)

}// of namespace ContainerServices
} // of namespace componentlib

/************************************************************
 End of LifeCycle class body
 ************************************************************/
