// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_StdPorts_Crun_BODY

/************************************************************
 Crun class body
 ************************************************************/

// include associated header file
#include "componentlib/StdPorts/Crun.h"

// Derived includes directives

namespace componentlib {
namespace StdPorts {

// static attributes (if any)

}// of namespace StdPorts
} // of namespace componentlib

/************************************************************
 End of Crun class body
 ************************************************************/
