// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_STDPORTS_CSTART_H
#define COMPONENTLIB_STDPORTS_CSTART_H

/************************************************************
 Cstart class header
 ************************************************************/

#include "componentlib/StdPorts/Pkg_StdPorts.h"

namespace componentlib {
namespace StdPorts {

/************************************************************/
/**
 * 
 */
class Cstart {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace StdPorts
} // of namespace componentlib

/************************************************************
 End of Cstart class header
 ************************************************************/

#endif
