// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_COMPONENTS_PUSHCONSUMER_PUSHCONSUMER_IMPL_H
#define PRODUCERCONSUMER_COMPONENTS_PUSHCONSUMER_PUSHCONSUMER_IMPL_H

/************************************************************
 PushConsumer_impl class header
 ************************************************************/

#include "ProducerConsumer/components/PushConsumer/Pkg_PushConsumer.h"

#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Push_PubData.h"
#include "componentlib/ContainerServices/LifeCycle.h"
#include "sysinterfaces/ILifeCycle.h"

namespace ProducerConsumer {
namespace components {
namespace interfaces {
struct PubData;
}
}
}

namespace ProducerConsumer {
namespace components {
namespace PushConsumer {

/************************************************************/
/**
 * 
 */
class PushConsumer_impl: public ::sysinterfaces::ILifeCycle,
		public ::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData,
		public ::componentlib::ContainerServices::LifeCycle {
public:

	/**
	 * 
	 */
	void activate();

	/**
	 * 
	 * @param data 
	 */
	void push(::ProducerConsumer::components::interfaces::PubData /*in*/data);

	/**
	 * 
	 */
	void deactivate();

	/**
	 * 
	 */
	void configuration_complete();

	/**
	 * 
	 * @return ret 
	 */
	::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData* get_p();

	/**
	 * 
	 * @return ret 
	 */
	::sysinterfaces::ILifeCycle* get_lc();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace PushConsumer
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of PushConsumer_impl class header
 ************************************************************/

#endif
