// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_components_PushConsumer_PushConsumer_impl_BODY

/************************************************************
 PushConsumer_impl class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/components/PushConsumer/PushConsumer_impl.h"

// Derived includes directives
#include "ProducerConsumer/components/interfaces/PubData.h"
#include "ProducerConsumer/derivedTypes/ProducerConsumer/components/interfaces/Push_PubData.h"
#include "sysinterfaces/ILifeCycle.h"

// Include from Include declaration (body)
#include <iostream>
using namespace std;
// End of Include declaration (body)

namespace ProducerConsumer {
namespace components {
namespace PushConsumer {

// static attributes (if any)

/**
 * 
 */
void PushConsumer_impl::activate() {
	cout << "initialization of push consumer" << endl;
}

/**
 * 
 * @param data 
 */
void PushConsumer_impl::push(
		::ProducerConsumer::components::interfaces::PubData /*in*/data) {
	cout << "received data: x = " << data.x << " y = " << data.y << endl;
}

/**
 * 
 */
void PushConsumer_impl::deactivate() {
}

/**
 * 
 */
void PushConsumer_impl::configuration_complete() {
}

/**
 * 
 * @return ret 
 */
::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData* PushConsumer_impl::get_p() {
	return this;
}

/**
 * 
 * @return ret 
 */
::sysinterfaces::ILifeCycle* PushConsumer_impl::get_lc() {
	return this;
}

} // of namespace PushConsumer
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of PushConsumer_impl class body
 ************************************************************/
