// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_PortKinds_PullConsumer_BODY

/************************************************************
 PullConsumer class body
 ************************************************************/

// include associated header file
#include "componentlib/PortKinds/PullConsumer.h"

// Derived includes directives

namespace componentlib {
namespace PortKinds {

// static attributes (if any)

}// of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PullConsumer class body
 ************************************************************/
