// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_PORTKINDS_PULLCONSUMER_H
#define COMPONENTLIB_PORTKINDS_PULLCONSUMER_H

/************************************************************
 PullConsumer class header
 ************************************************************/

#include "componentlib/PortKinds/Pkg_PortKinds.h"

namespace componentlib {
namespace PortKinds {

/************************************************************/
/**
 * 
 */
class PullConsumer {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PullConsumer class header
 ************************************************************/

#endif
