// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define componentlib_PortKinds_PushProducer_BODY

/************************************************************
 PushProducer class body
 ************************************************************/

// include associated header file
#include "componentlib/PortKinds/PushProducer.h"

// Derived includes directives

namespace componentlib {
namespace PortKinds {

// static attributes (if any)

}// of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PushProducer class body
 ************************************************************/
