// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPONENTLIB_PORTKINDS_PUSHPRODUCER_H
#define COMPONENTLIB_PORTKINDS_PUSHPRODUCER_H

/************************************************************
 PushProducer class header
 ************************************************************/

#include "componentlib/PortKinds/Pkg_PortKinds.h"

namespace componentlib {
namespace PortKinds {

/************************************************************/
/**
 * 
 */
class PushProducer {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace PortKinds
} // of namespace componentlib

/************************************************************
 End of PushProducer class header
 ************************************************************/

#endif
