// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_platform_MonoNode_BODY

/************************************************************
 MonoNode class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/platform/MonoNode.h"

// Derived includes directives

namespace ProducerConsumer {
namespace platform {

// static attributes (if any)

}// of namespace platform
} // of namespace ProducerConsumer

/************************************************************
 End of MonoNode class body
 ************************************************************/
