// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_PLATFORM_MONONODE_H
#define PRODUCERCONSUMER_PLATFORM_MONONODE_H

/************************************************************
 MonoNode class header
 ************************************************************/

#include "ProducerConsumer/platform/Pkg_platform.h"

namespace ProducerConsumer {
namespace platform {

/************************************************************/
/**
 * 
 */
class MonoNode {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace platform
} // of namespace ProducerConsumer

/************************************************************
 End of MonoNode class header
 ************************************************************/

#endif
