// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef HELLOWORLDCPP_CLASSES_HELLOWORLD_H
#define HELLOWORLDCPP_CLASSES_HELLOWORLD_H

/************************************************************
 HelloWorld class header
 ************************************************************/

#include "HelloWorldCpp/classes/Pkg_classes.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "sysinterfaces/IStart.h"

namespace HelloWorldCpp {
namespace classes {

/************************************************************/
/**
 * Configuration attribute within the Hello World component. Its value is configured on the instance level.The operation "run" is defined in interface IRunnnable that is provided by the IStart port. The synchronisation mechanism in Qompass ("Sync. derived element", needs to be triggered by user) adds a corresponding "derived" operation to the class 
 */
class HelloWorld: public ::sysinterfaces::IStart {
public:
	/**
	 * 
	 */
	::PrimitiveTypes::String message;

	/**
	 * 
	 */
	void run();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace classes
} // of namespace HelloWorldCpp

/************************************************************
 End of HelloWorld class header
 ************************************************************/

#endif
