// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define HelloWorldCpp_classes_HelloWorld_BODY

/************************************************************
 HelloWorld class body
 ************************************************************/

// include associated header file
#include "HelloWorldCpp/classes/HelloWorld.h"

// Derived includes directives
#include "sysinterfaces/IStart.h"

// Include from Include declaration (body)
#include <iostream>
using namespace std;
// End of Include declaration (body)

namespace HelloWorldCpp {
namespace classes {

// static attributes (if any)

/**
 * 
 */
void HelloWorld::run() {
	cout << "Hello world: " << message << endl;
}

} // of namespace classes
} // of namespace HelloWorldCpp

/************************************************************
 End of HelloWorld class body
 ************************************************************/
