// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_COMPONENTS_SYSTEM_SYSTEMPUSH_IMPL_H
#define PRODUCERCONSUMER_COMPONENTS_SYSTEM_SYSTEMPUSH_IMPL_H

/************************************************************
 SystemPush_impl class header
 ************************************************************/

#include "ProducerConsumer/components/System/Pkg_System.h"

#include "ProducerConsumer/components/Producer/Producer_impl.h"
#include "ProducerConsumer/components/PushConsumer/PushConsumer_impl.h"

namespace ProducerConsumer {
namespace components {
namespace System {

/************************************************************/
/**
 * The push consumer provides the interface that the producer uses (requires), no specific connector is required
 */
class SystemPush_impl {
public:
	/**
	 * 
	 */
	::ProducerConsumer::components::Producer::Producer_impl prod;
	/**
	 * 
	 */
	::ProducerConsumer::components::PushConsumer::PushConsumer_impl con;

	/**
	 * 
	 */
	void createConnections();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace System
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of SystemPush_impl class header
 ************************************************************/

#endif
