// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ProducerConsumer_components_System_SystemPull_impl_BODY

/************************************************************
 SystemPull_impl class body
 ************************************************************/

// include associated header file
#include "ProducerConsumer/components/System/SystemPull_impl.h"

// Derived includes directives

namespace ProducerConsumer {
namespace components {
namespace System {

// static attributes (if any)

/**
 * 
 */
void SystemPull_impl::createConnections() {
	// realization of connector <c fifoconnector 0>
	prod.connect_q(fifoconnector.get_pushP());

	// realization of connector <c fifoconnector 1>
	con.connect_p(fifoconnector.get_pullC());

}

} // of namespace System
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of SystemPull_impl class body
 ************************************************************/
