// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPLEXSM_CLASSES_INTERFACES_ADD_H
#define COMPLEXSM_CLASSES_INTERFACES_ADD_H

/************************************************************
 Add class header
 ************************************************************/

#include "ComplexSM/classes/Interfaces/Pkg_Interfaces.h"

namespace ComplexSM {
namespace classes {
namespace Interfaces {

/************************************************************/
/**
 * 
 */
class Add {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Interfaces
} // of namespace classes
} // of namespace ComplexSM

/************************************************************
 End of Add class header
 ************************************************************/

#endif
