// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef COMPLEXSM_CLASSES_INTERFACES_MULT_H
#define COMPLEXSM_CLASSES_INTERFACES_MULT_H

/************************************************************
 Mult class header
 ************************************************************/

#include "ComplexSM/classes/Interfaces/Pkg_Interfaces.h"

namespace ComplexSM {
namespace classes {
namespace Interfaces {

/************************************************************/
/**
 * 
 */
class Mult {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Interfaces
} // of namespace classes
} // of namespace ComplexSM

/************************************************************
 End of Mult class header
 ************************************************************/

#endif
