<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Codegen" nsURI="http://www.eclipse.org/papyrus/Codegen/1" nsPrefix="Codegen">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationMode" ordered="false"
        lowerBound="1" eType="#//GenerationModeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceFolder" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GenerationModeKind">
    <eLiterals name="Batch"/>
    <eLiterals name="Incremental" value="1"/>
  </eClassifiers>
</ecore:EPackage>
