// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ClientServerZMQ_platform_MonoNode_BODY

/************************************************************
 MonoNode class body
 ************************************************************/

// include associated header file
#include <ClientServerZMQ/platform/MonoNode.h>

// Derived includes directives

namespace platform {

// static attributes (if any)

}// of namespace platform

/************************************************************
 End of MonoNode class body
 ************************************************************/