// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_PLATFORM_MONONODE_H
#define CLIENTSERVERZMQ_PLATFORM_MONONODE_H

/************************************************************
 MonoNode class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/platform/Pkg_platform.h>

namespace platform {

/************************************************************/
/**
 * 
 */

class MonoNode {

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace platform

/************************************************************
 End of MonoNode class header
 ************************************************************/

#endif
