// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_PLATFORM_TCPNODE_H
#define CLIENTSERVERZMQ_PLATFORM_TCPNODE_H

/************************************************************
 TCPNode class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/platform/Pkg_platform.h>

#include <ZMQ_lib/ZMQSocketRuntime/TCPIPConfig.h>

namespace platform {

/************************************************************/
/**
 * 
 */

class TCPNode: public ::ZMQ_lib::ZMQSocketRuntime::TCPIPConfig {

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace platform

/************************************************************
 End of TCPNode class header
 ************************************************************/

#endif
