// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ClientServerZMQ_platform_TCPNode_BODY

/************************************************************
 TCPNode class body
 ************************************************************/

// include associated header file
#include <ClientServerZMQ/platform/TCPNode.h>

// Derived includes directives

namespace platform {

// static attributes (if any)

}// of namespace platform

/************************************************************
 End of TCPNode class body
 ************************************************************/