// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ClientServerZMQ_components_System_System_impl_BODY

/************************************************************
 System_impl class body
 ************************************************************/

// include associated header file
#include <ClientServerZMQ/components/System/System_impl.h>

// Derived includes directives

namespace components {
namespace System {

// static attributes (if any)

}// of namespace System
} // of namespace components

/************************************************************
 End of System_impl class body
 ************************************************************/