// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CLIENTSERVERZMQ_COMPONENTS_SYSTEM_SYSTEM_IMPL_H
#define CLIENTSERVERZMQ_COMPONENTS_SYSTEM_SYSTEM_IMPL_H

/************************************************************
 System_impl class header
 ************************************************************/

/* Owner package header include                             */
#include <ClientServerZMQ/components/System/Pkg_System.h>

#include <ClientServerZMQ/components/Server/CServer_impl.h>

#include <ClientServerZMQ/components/Client/CClient_impl.h>

namespace components {
namespace System {

/************************************************************/
/**
 * 
 */

class System_impl {

public:

	/**
	 * 
	 */
	::ClientServerZMQ::components::Server::CServer_impl server;

	/**
	 * 
	 */
	::ClientServerZMQ::components::Client::CClient_impl client;

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

} // of namespace System
} // of namespace components

/************************************************************
 End of System_impl class header
 ************************************************************/

#endif
