// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef PRODUCERCONSUMER_COMPONENTS_PRODUCER_PRODUCER_IMPL_H
#define PRODUCERCONSUMER_COMPONENTS_PRODUCER_PRODUCER_IMPL_H

/************************************************************
 Producer_impl class header
 ************************************************************/

#include "ProducerConsumer/components/Producer/Pkg_Producer.h"

#include "componentlib/StdPorts/Cstart.h"
#include "sysinterfaces/IStart.h"

namespace ProducerConsumer {
namespace derivedTypes {
namespace ProducerConsumer {
namespace components {
namespace interfaces {
class Push_PubData;
}
}
}
}
}

namespace ProducerConsumer {
namespace components {
namespace Producer {

/************************************************************/
/**
 * 
 */
class Producer_impl: public ::sysinterfaces::IStart,
		public ::componentlib::StdPorts::Cstart {
public:
	/**
	 * 
	 */
	::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData* q;

	/**
	 * 
	 */
	void run();

	/**
	 * 
	 * @return ret 
	 */
	::sysinterfaces::IStart* get_start();

	/**
	 * 
	 * @param ref 
	 */
	void connect_q(
			::ProducerConsumer::derivedTypes::ProducerConsumer::components::interfaces::Push_PubData* /*in*/ref);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Producer
} // of namespace components
} // of namespace ProducerConsumer

/************************************************************
 End of Producer_impl class header
 ************************************************************/

#endif
